# Site settings
title: Tom Hockett
description: Get at me
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://tomhockett.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tom Hockett
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer
email: tom.hockett@gmail.com
twitter_username: tomhockett
github_username: tomhockett

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
